In [3]:
import numpy as np

%precision 3

'%.3f'

## 配列

In [3]:
# 配列の作成
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [4]:
data.dtype

dtype('int64')

## 次元数と要素数

In [5]:
print('次元数:', data.ndim)
print('要素数:', data.size)

次元数: 1
要素数: 10


## 要素の計算

In [6]:
# それぞれの数字を5倍
print('要素の計数倍:', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) * 5)
# それぞれの要素同士での演算
print('掛け算:', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) * np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
print('累乗:', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) ** 2)
print('割り算:', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) / np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

要素の計数倍: [ 5 10 15 20 25 30 35 40 45 50]
掛け算: [  1   4   9  16  25  36  49  64  81 100]
累乗: [  1   4   9  16  25  36  49  64  81 100]
割り算: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 並び替え (ソーティング)

In [7]:
# 現在の値を表示
print('現在値：', data)
# ソートした結果を表示
data.sort()
print('ソート後：', data)

data[::-1].sort()
print('ソート後（降順）：', data)

現在値： [ 9  2  3  4 10  6  7  8  1  5]
ソート後： [ 1  2  3  4  5  6  7  8  9 10]
ソート後（降順）： [10  9  8  7  6  5  4  3  2  1]


## 最小、最大、合計、積み上げ

In [8]:
# 最小値
print('Min:', data.min())
# 最大値
print('Max:', data.max())
# 合計
print('Sum:', data.sum())
# 積み上げ
print('Cum:', data.cumsum())

Min: 1
Max: 10
Sum: 55
Cum: [10 19 27 34 40 45 49 52 54 55]


## 乱数

In [9]:
# インポート
import numpy.random as random
# 乱数のシードの設定
random.seed(0)
# 正規分布（平均0、分散1）の乱数を10個発生
rnd_data= random.randn(10)
print('乱数10個の配列:', rnd_data)

乱数10個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


## データをランダムに抽出

In [10]:
# 抽出対象データ
data = np.array([9,2,3,4,10,6,7,8,1,5])
# ランダム抽出# 10個を抽出（重複あり、復元抽出）
print(random.choice(data, 10))
# 10個を抽出（重複なし、非復元抽出)
print(random.choice(data, 10, replace = False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


## ちょっと一息 (確かめてみよう！)

In [11]:
# Nは乱数の発生数、10の6乗
N = 10**6
# Python版 (以下のrange(N)は0からN-1までの整数を用意しています。 
# 「_」は、代入した値を参照しないときに使う慣例的な変数名です。
# たとえば、for a in range(N)と書くのと同じですが、aと書くと、その値をあとで使うように見えるので、
# その値を参照しないときは、for _ in range(N)のように慣例的に書く書き方です
normal_data = [random.random() for _ in range(N)]
# Numpy版
numpy_random_data = np.array(normal_data)
# calc time :合計値
# ふつうの処理
%timeit sum(normal_data)
# Numpyを使った処理
%timeit np.sum(numpy_random_data)

3.87 ms ± 159 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
546 µs ± 36.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 行列

In [12]:
# 0～8までの整数を発生
print(np.arange(9))
# 上記を３×３の行列に分割
array1 = np.arange(9).reshape(3,3)
print(array1)
#1行目表示
print('1行目：',array1[0,:])
#1列目表示
print('1列目：',array1[:,0])

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
1行目： [0 1 2]
1列目： [0 3 6]


## 行列の演算

In [13]:
# 9～17までの3×3の行列作成
array2 = np.arange(9, 18).reshape(3,3)
print(array2)
#行列の積
print(np.dot(array1, array2))
#要素の積
print(array1 * array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


## 要素が0や1の行列

In [16]:
#要素がすべて０で，データ型は64ビット整数
print(np.zeros((2, 3), dtype= np.int64))
#要素がすべて１の64ビット浮動小数
print(np.ones((2, 3), dtype= np.float64))




[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Scipyの基礎

## Scipyライブラリのインポート

In [2]:
# Scipyライブラリの読み込み
import scipy as sp
# 線形代数用のライブラリ
import scipy.linalg as linalg
# 最適化計算（最小値）用の関数
from scipy.optimize import minimize_scalar




## 行列式と逆行列

In [4]:
matrix = np.array([[1,-1,-1], [-1,1,-1], [-1,-1,1]])

# 行列式
print('行列式')
print(linalg.det(matrix))

# 逆行列
print('逆行列')
print(linalg.inv(matrix))

#もとの行列と逆行列の積を確認
print(matrix.dot(linalg.inv(matrix)))





行列式
-4.0
逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 固有値と固有ベクトル

In [5]:
# 固有値と固有ベクトル
eig_value, eig_vector= linalg.eig(matrix)

# 固有値と固有ベクトル
print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)


固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]


## 方程式の解

In [7]:
# 関数の定義
def my_function(x):
    return (x**2 + 2*x + 1)
# ニュートン法の読み込み
from scipy.optimize import newton
# 計算実行
print(newton(my_function,0))

-0.9999999852953906


## 最小値

In [8]:
# 計算実行
print(minimize_scalar(my_function, method = 'Brent'))

     fun: 0.0
 message: '\nOptimization terminated successfully;\nThe returned value satisfies the termination criteria\n(using xtol = 1.48e-08 )'
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002
